---
title: "Manipulative quantifier use (free production) - Data exploration (03-02-2020)"
output: html_document
---

```{r include=FALSE}
library(plyr)
library(tidyverse)

# Import data
d <- read_csv("./data/results-free-prod-30-01-coded.csv") %>% 
  select(-X5)

d$row_number <- as.factor(d$row_number)

d <- plyr::rename(d, c("type-sub"="type_sub", "type-obj"="type_obj"))

d$type_sub <- as.factor(d$type_sub)
d$type_obj <- as.factor(d$type_obj)
d$pred <- as.factor(d$pred)
d$framing <- factor(d$framing, levels = c("low", "high"))

d <- d %>% 
  mutate(quant_comb = case_when(type_sub == "non-num" & type_obj == "non-num" ~ "non-num2",
                                type_sub == "non-num" & type_obj == "num" ~ "non-num_num",
                                type_sub == "non-num" & type_obj == "no" ~ "non-num_no",
                                type_sub == "num" & type_obj == "non-num" ~ "num_non-num",
                                type_sub == "num" & type_obj == "num" ~ "num2",
                                type_sub == "num" & type_obj == "no" ~ "num_no",
                                TRUE ~ "other"))
 
d2 <- d %>% 
  drop_na(type_sub, type_obj)
```

***

Quantifier combination, as shown in terms of (1) the whole data, (2) the predicate types, and (3) the experimental conditons.

```{r fig.align='center', echo=FALSE, warning=FALSE}
d2 %>% 
  ggplot(aes(x = quant_comb, y = ..prop.., group = 1), stat = "count") + 
  geom_bar() +
  coord_flip() +
  scale_y_continuous(labels = scales::percent_format())

d2 %>%
  filter(pred != "NA") %>% 
  ggplot(aes(x = quant_comb, y = ..prop.., group = 1), stat = "count") +
  facet_wrap( ~ pred) +
  geom_bar() +
  coord_flip() +
  scale_y_continuous(labels = scales::percent_format())

d2 %>%
  filter(pred != "NA") %>% 
  ggplot(aes(x = quant_comb, y = ..prop.., group = 1), stat = "count") +
  facet_wrap( ~ framing) +
  geom_bar() +
  coord_flip() +
  scale_y_continuous(labels = scales::percent_format())

```

***

Predicate types, as shown in terms of (1) the whole data and (2) the experimental conditions.

```{r fig.align='center', echo=FALSE, warning=FALSE}
d2 %>%
  filter(pred != "NA") %>% 
  ggplot(aes(x = pred, y = ..prop.., group = 1), stat = "count") + 
  geom_bar() +
  scale_y_continuous(labels = scales::percent_format())

d2 %>%
  filter(pred != "NA") %>% 
  ggplot(aes(x = pred, y = ..prop.., group = 1), stat = "count") +
  facet_wrap( ~ framing) +
  geom_bar() +
  scale_y_continuous(labels = scales::percent_format())
```

